//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskever.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTexts() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taskever.Localization.Resources.AppTexts", typeof(AppTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Display name 的本地化字符串。
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello World! 的本地化字符串。
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My friends 的本地化字符串。
        /// </summary>
        internal static string MyFriends {
            get {
                return ResourceManager.GetString("MyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My tasks 的本地化字符串。
        /// </summary>
        internal static string MyTasks {
            get {
                return ResourceManager.GetString("MyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 See all friends 的本地化字符串。
        /// </summary>
        internal static string SeeAllFriends {
            get {
                return ResourceManager.GetString("SeeAllFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 See all tasks 的本地化字符串。
        /// </summary>
        internal static string SeeAllTasks {
            get {
                return ResourceManager.GetString("SeeAllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sender address 的本地化字符串。
        /// </summary>
        internal static string SenderAddress {
            get {
                return ResourceManager.GetString("SenderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server address 的本地化字符串。
        /// </summary>
        internal static string ServerAddress {
            get {
                return ResourceManager.GetString("ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server port 的本地化字符串。
        /// </summary>
        internal static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Above Normal 的本地化字符串。
        /// </summary>
        internal static string TaskPriority_AboveNormal {
            get {
                return ResourceManager.GetString("TaskPriority_AboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Below Normal 的本地化字符串。
        /// </summary>
        internal static string TaskPriority_BelowNormal {
            get {
                return ResourceManager.GetString("TaskPriority_BelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        internal static string TaskPriority_High {
            get {
                return ResourceManager.GetString("TaskPriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        internal static string TaskPriority_Low {
            get {
                return ResourceManager.GetString("TaskPriority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        internal static string TaskPriority_Normal {
            get {
                return ResourceManager.GetString("TaskPriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Private 的本地化字符串。
        /// </summary>
        internal static string TaskPrivacy_Private {
            get {
                return ResourceManager.GetString("TaskPrivacy_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protected 的本地化字符串。
        /// </summary>
        internal static string TaskPrivacy_Protected {
            get {
                return ResourceManager.GetString("TaskPrivacy_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        internal static string TaskState_Completed {
            get {
                return ResourceManager.GetString("TaskState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string TaskState_New {
            get {
                return ResourceManager.GetString("TaskState_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkingOn 的本地化字符串。
        /// </summary>
        internal static string TaskState_WorkingOn {
            get {
                return ResourceManager.GetString("TaskState_WorkingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User nama 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
